module ProbablyWorthWatching
end

require_relative 'probably_worth_watching/filter_chain'
require_relative 'probably_worth_watching/tweet'
require_relative 'probably_worth_watching/tweet_with_links'
require_relative 'probably_worth_watching/tweet_with_videos'
require_relative 'probably_worth_watching/finds_links_filter'
require_relative 'probably_worth_watching/finds_videos_filter'
require_relative 'probably_worth_watching/video_extractors'
