class Rubyists
  def initialize
  end

  def twitter_handles
    %w(
      JEG2
      avdi
      bascule
      knewter
      adamgamble
      chadfowler
      defunkt
      pragdave
      david_a_black
      drnic
      dhh
      drbrain
      evanphx
      ezmobius
      AkitaOnRails
      topfunky
      gilesgoatboy
      jimweirich
      peterc
      wycats
      _solnic_
      the_zenspider
      mfeathers
      konstantinhaase
      r00k
      dkubb
      eliseworthy
      brynary
      geeksam
      kytrinyx
      mattwynne
      kevinrutherford
      sarahmei
      mpapis
      sandimetz
      steveklabnik
      jstorimer
      russolsen
      PragmaticAndy
      merbist
      edavis10
      KentBeck
      garybernhardt
      noelrap
      joshsusser
      j3
      ryandotsmith
      brixen
      ReinH
      mattyoho
      indirect
      mislav
      bscofield
      greggpollack
      dbrady
      MilesForrest
    )
  end
end
